[project]
name = "boatforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cartopy>=0.25.0",
    "dask>=2026.7.0",
    "eccodes>=2.47.0",
    "eccodeslib>=2.47.3.22",
    "h3>=4.5.0",
    "h5py>=3.16.0",
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "pyqt6>=6.11.0",
    "pyvista>=0.48.4",
    "scipy>=1.18.0",
    "xarray>=2026.7.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
